### ISSUE TITLE
Put map on proposals page and add pin markers

### ISSUE THREAD

**Issue by pckerneis** [Franck106/openworker-front#58]

**Comment by pckerneis** [comment]
![map](https://user-images.githubusercontent.com/29951517/94345869-3d7a0c80-0029-11eb-8a4c-3a13e9c07500.PNG)

**Comment by duvochel** [comment]
done with #48

**Comment by pckerneis** [comment]
Okay, il reste encore à déplacer la map sur l'écran catalogue et le connecter au champs de recherche et filter les pins visibles en fonction des résultats, si on veut reproduire le comportement d'avant. Et les clics sur le pin permettait de faire un focus sur l'annonce associée au pin. On garde tout ça ou on oublie ?

**Comment by pckerneis** [comment]
Pour rappel de l'ancien comportement
![comportement_map](https://user-images.githubusercontent.com/29951517/94347842-05c69100-0038-11eb-94fd-6ba55a17e2c8.gif)

**Comment by duvochel** [comment]
oui c'était super ça! si t'es chaud c'est évidemment bienvenu. Je pense que ça se monte sur ce qui est déjà installé avec google-map component non?

**Comment by pckerneis** [comment]
Ok je vais regarder demain si je peux récupérer du code de l'ancien front en espérant que ce soit facile à refaire en Angular

**Comment by duvochel** [comment]
après si tu trouves que c'est plus simple de tout remettre avec le code d'avant vas-y aussi pas de problème
